# Generated by Django 2.0.6 on 2020-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'unknown')], default=1),
        ),
    ]
