# Generated by Django 2.0.6 on 2020-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=32)),
                ('stu_age', models.IntegerField()),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], default=1)),
                ('stu_img', models.ImageField(default='pic/1.jpg', upload_to='pic')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'drf_student',
            },
        ),
    ]
